In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [41]:
data = pd.read_csv("pima-data.csv")

In [42]:
data.head()

num_preg  glucose_conc  diastolic_bp  thickness  insulin   bmi  diab_pred  \
0         6           148            72         35        0  33.6      0.627   
1         1            85            66         29        0  26.6      0.351   
2         8           183            64          0        0  23.3      0.672   
3         1            89            66         23       94  28.1      0.167   
4         0           137            40         35      168  43.1      2.288   

   age    skin  diabetes  
0   50  1.3790      True  
1   31  1.1426     False  
2   32  0.0000      True  
3   21  0.9062     False  
4   33  1.3790      True

In [43]:
data.shape

(768, 10)

In [44]:
data.isnull().sum()  #Checking if there are any NULL values

num_preg        0
glucose_conc    0
diastolic_bp    0
thickness       0
insulin         0
bmi             0
diab_pred       0
age             0
skin            0
diabetes        0
dtype: int64

In [45]:
data.dtypes  #Datatypes of each column 

num_preg          int64
glucose_conc      int64
diastolic_bp      int64
thickness         int64
insulin           int64
bmi             float64
diab_pred       float64
age               int64
skin            float64
diabetes           bool
dtype: object

In [46]:
diabetes_map = {True: 1, False: 0}

In [47]:
data['diabetes'] = data['diabetes'].map(diabetes_map)

In [48]:
data.head()

num_preg  glucose_conc  diastolic_bp  thickness  insulin   bmi  diab_pred  \
0         6           148            72         35        0  33.6      0.627   
1         1            85            66         29        0  26.6      0.351   
2         8           183            64          0        0  23.3      0.672   
3         1            89            66         23       94  28.1      0.167   
4         0           137            40         35      168  43.1      2.288   

   age    skin  diabetes  
0   50  1.3790         1  
1   31  1.1426         0  
2   32  0.0000         1  
3   21  0.9062         0  
4   33  1.3790         1

In [49]:
print("total number of rows : {0}".format(len(data)))
print("number of rows missing glucose_conc: {0}".format(len(data.loc[data['glucose_conc'] == 0])))
print("number of rows missing diastolic_bp: {0}".format(len(data.loc[data['diastolic_bp'] == 0])))
print("number of rows missing insulin: {0}".format(len(data.loc[data['insulin'] == 0])))
print("number of rows missing bmi: {0}".format(len(data.loc[data['bmi'] == 0])))
print("number of rows missing thickness: {0}".format(len(data.loc[data['thickness'] == 0])))
print("number of rows missing diab_pred: {0}".format(len(data.loc[data['diab_pred'] == 0])))
print("number of rows missing age: {0}".format(len(data.loc[data['age'] == 0])))
print("number of rows missing skin: {0}".format(len(data.loc[data['skin'] == 0])))

total number of rows : 768
number of rows missing glucose_conc: 5
number of rows missing diastolic_bp: 35
number of rows missing insulin: 374
number of rows missing bmi: 11
number of rows missing thickness: 227
number of rows missing diab_pred: 0
number of rows missing age: 0
number of rows missing skin: 227


In [50]:
data['glucose_conc']=data['glucose_conc'].replace(0,data['glucose_conc'].mean())
data['diastolic_bp']=data['diastolic_bp'].replace(0,data['diastolic_bp'].mean())
data['insulin']=data['insulin'].replace(0,data['insulin'].mean())
data['bmi']=data['bmi'].replace(0,data['bmi'].mean())
data['skin']=data['skin'].replace(0,data['skin'].mean())
data['thickness']=data['thickness'].replace(0,data['thickness'].mean())

In [51]:
data.head()

num_preg  glucose_conc  diastolic_bp  thickness     insulin   bmi  \
0         6         148.0          72.0  35.000000   79.799479  33.6   
1         1          85.0          66.0  29.000000   79.799479  26.6   
2         8         183.0          64.0  20.536458   79.799479  23.3   
3         1          89.0          66.0  23.000000   94.000000  28.1   
4         0         137.0          40.0  35.000000  168.000000  43.1   

   diab_pred  age      skin  diabetes  
0      0.627   50  1.379000         1  
1      0.351   31  1.142600         0  
2      0.672   32  0.809136         1  
3      0.167   21  0.906200         0  
4      2.288   33  1.379000         1

In [52]:
target_name='diabetes'
q=data[target_name]
p=data.drop(target_name,axis=1)

In [53]:
p.head()

num_preg  glucose_conc  diastolic_bp  thickness     insulin   bmi  \
0         6         148.0          72.0  35.000000   79.799479  33.6   
1         1          85.0          66.0  29.000000   79.799479  26.6   
2         8         183.0          64.0  20.536458   79.799479  23.3   
3         1          89.0          66.0  23.000000   94.000000  28.1   
4         0         137.0          40.0  35.000000  168.000000  43.1   

   diab_pred  age      skin  
0      0.627   50  1.379000  
1      0.351   31  1.142600  
2      0.672   32  0.809136  
3      0.167   21  0.906200  
4      2.288   33  1.379000

In [54]:
q.head()

0    1
1    0
2    1
3    0
4    1
Name: diabetes, dtype: int64

In [55]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(p)
SSX=scaler.transform(p)

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_tr,x_te,y_tr,y_te = train_test_split(p,q,test_size=0.30)  #Splitting the data into Train and Test data
print(x_tr.shape)
print(x_te.shape)
print(y_tr.shape)
print(y_te.shape)

(537, 9)
(231, 9)
(537,)
(231,)


In [58]:
from sklearn.linear_model import LogisticRegression #Implementing Logistic Regression

In [59]:
m_1 = LogisticRegression(solver='liblinear')
m_1.fit(x_tr,y_tr)

LogisticRegression(solver='liblinear')

In [60]:
ypred_m_1 = m_1.predict(x_te)
print(ypred_m_1)
print('Training score',m_1.score(x_tr,y_tr))
print('Testing score',m_1.score(x_te,y_te))

[0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 0 1 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 1
 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0
 1 0 0 1 0 0 0 0 0]
Training score 0.7783985102420856
Testing score 0.7316017316017316


In [61]:
from sklearn.metrics import confusion_matrix, classification_report

In [62]:
cm_m_1 = confusion_matrix(y_te,ypred_m_1)
print(cm_m_1)
print(classification_report(y_te,ypred_m_1))

[[127  31]
 [ 31  42]]
              precision    recall  f1-score   support

           0       0.80      0.80      0.80       158
           1       0.58      0.58      0.58        73

    accuracy                           0.73       231
   macro avg       0.69      0.69      0.69       231
weighted avg       0.73      0.73      0.73       231



In [63]:
from sklearn.neighbors import KNeighborsClassifier  #Implementing KNN Classification

In [64]:
m_2 = KNeighborsClassifier(n_neighbors=13) 
m_2.fit(x_tr,y_tr)

KNeighborsClassifier(n_neighbors=13)

In [65]:
ypred_m_2 = m_2.predict(x_te)
print(ypred_m_2)
print('Training score',m_2.score(x_tr,y_tr))
print('Testing score',m_2.score(x_te,y_te))

[0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0
 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 1 1 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0
 1 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0
 1 0 0 0 0 0 0 0 0]
Training score 0.770949720670391
Testing score 0.7316017316017316


In [66]:
cm_m_2 = confusion_matrix(y_te,ypred_m_2)
print(cm_m_2)
print(classification_report(y_te,ypred_m_2))

[[125  33]
 [ 29  44]]
              precision    recall  f1-score   support

           0       0.81      0.79      0.80       158
           1       0.57      0.60      0.59        73

    accuracy                           0.73       231
   macro avg       0.69      0.70      0.69       231
weighted avg       0.74      0.73      0.73       231



In [67]:
from sklearn.tree import DecisionTreeClassifier  #Implementing Decision Tree Classification

In [68]:
m_3=DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=12)
m_3.fit(x_tr,y_tr)

DecisionTreeClassifier(max_depth=4, min_samples_split=12)

In [69]:
ypred_m_3 = m_3.predict(x_te)
print(ypred_m_3)
print('Training score',m_3.score(x_tr,y_tr))
print('Testing score',m_3.score(x_te,y_te))

[0 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0
 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 1 1
 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 1
 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 1 0 0 1 0 0 0 0 0]
Training score 0.8044692737430168
Testing score 0.7532467532467533


In [70]:
cm_m_3 = confusion_matrix(y_te,ypred_m_3)
print(cm_m_3)
print(classification_report(y_te,ypred_m_3)) 

[[132  26]
 [ 31  42]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       158
           1       0.62      0.58      0.60        73

    accuracy                           0.75       231
   macro avg       0.71      0.71      0.71       231
weighted avg       0.75      0.75      0.75       231



In [71]:
from sklearn.ensemble import RandomForestClassifier  #Implementing Random Forest Classification

In [72]:
m_4=RandomForestClassifier(n_estimators=80,criterion='entropy',max_depth=6,min_samples_split=15)
m_4.fit(x_tr,y_tr)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_split=15,
                       n_estimators=80)

In [73]:
ypred_m_4 = m_4.predict(x_te)
print(ypred_m_4)
print('Training score',m_4.score(x_tr,y_tr))
print('Testing score',m_4.score(x_te,y_te)) 

[0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0
 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 0
 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 0]
Training score 0.8715083798882681
Testing score 0.7359307359307359


In [74]:
cm_m_4 = confusion_matrix(y_te,ypred_m_4)
print(cm_m_4)
print(classification_report(y_te,ypred_m_4))

[[127  31]
 [ 30  43]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81       158
           1       0.58      0.59      0.59        73

    accuracy                           0.74       231
   macro avg       0.69      0.70      0.70       231
weighted avg       0.74      0.74      0.74       231



In [75]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_tr,y_tr)

SVC()

In [76]:
ypred_m_5 = sv.predict(x_te)
print(ypred_m_5)
print('Training score',sv.score(x_tr,y_tr))
print('Testing score',sv.score(x_te,y_te))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0
 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 1
 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0
 1 0 0 1 0 0 0 0 0]
Training score 0.7653631284916201
Testing score 0.7575757575757576


In [77]:
cm_m_5 = confusion_matrix(y_te,ypred_m_5)
print(cm_m_4)
print(classification_report(y_te,ypred_m_5))

[[127  31]
 [ 30  43]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       158
           1       0.64      0.52      0.58        73

    accuracy                           0.76       231
   macro avg       0.72      0.69      0.70       231
weighted avg       0.75      0.76      0.75       231

